# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_permission_is_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='is_menu',
            new_name='menu',
        ),
    ]
